{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting cupy\n",
      "  Using cached cupy-12.2.0.tar.gz (2.0 MB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25ldone\n",
      "\u001b[?25h  Installing backend dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Preparing metadata (pyproject.toml) ... \u001b[?25lerror\n",
      "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "  \n",
      "  \u001b[31m×\u001b[0m \u001b[32mPreparing metadata \u001b[0m\u001b[1;32m(\u001b[0m\u001b[32mpyproject.toml\u001b[0m\u001b[1;32m)\u001b[0m did not run successfully.\n",
      "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "  \u001b[31m╰─>\u001b[0m \u001b[31m[61 lines of output]\u001b[0m\n",
      "  \u001b[31m   \u001b[0m Clearing directory: /tmp/pip-install-66ea4jj2/cupy_6eabe6fe111c476894fc65a07c721595/cupy/.data\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m -------- Configuring Module: cuda --------\n",
      "  \u001b[31m   \u001b[0m /usr/bin/ld: cannot find -lcuda: No such file or directory\n",
      "  \u001b[31m   \u001b[0m collect2: error: ld returned 1 exit status\n",
      "  \u001b[31m   \u001b[0m Cannot build a stub file.\n",
      "  \u001b[31m   \u001b[0m Original error: command '/usr/bin/x86_64-linux-gnu-g++' failed with exit code 1\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m ************************************************************\n",
      "  \u001b[31m   \u001b[0m * CuPy Configuration Summary                               *\n",
      "  \u001b[31m   \u001b[0m ************************************************************\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m Build Environment:\n",
      "  \u001b[31m   \u001b[0m   Include directories: ['/usr/local/cuda/include/cub', '/tmp/pip-install-66ea4jj2/cupy_6eabe6fe111c476894fc65a07c721595/cupy/_core/include', '/usr/local/cuda/include']\n",
      "  \u001b[31m   \u001b[0m   Library directories: ['/usr/local/cuda/lib64']\n",
      "  \u001b[31m   \u001b[0m   nvcc command       : ['/usr/local/cuda/bin/nvcc']\n",
      "  \u001b[31m   \u001b[0m   hipcc command      : (not found)\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m Environment Variables:\n",
      "  \u001b[31m   \u001b[0m   CFLAGS          : (none)\n",
      "  \u001b[31m   \u001b[0m   LDFLAGS         : (none)\n",
      "  \u001b[31m   \u001b[0m   LIBRARY_PATH    : (none)\n",
      "  \u001b[31m   \u001b[0m   CUDA_PATH       : (none)\n",
      "  \u001b[31m   \u001b[0m   NVCC            : (none)\n",
      "  \u001b[31m   \u001b[0m   HIPCC           : (none)\n",
      "  \u001b[31m   \u001b[0m   ROCM_HOME       : (none)\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m Modules:\n",
      "  \u001b[31m   \u001b[0m   cuda      : No\n",
      "  \u001b[31m   \u001b[0m     -> Cannot link libraries: ['cuda', 'cudart', 'cublas', 'cufft', 'curand', 'cusparse', 'nvrtc']\n",
      "  \u001b[31m   \u001b[0m     -> Check your LDFLAGS environment variable.\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m ERROR: CUDA could not be found on your system.\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m HINT: You are trying to build CuPy from source, which is NOT recommended for general use.\n",
      "  \u001b[31m   \u001b[0m       Please consider using binary packages instead.\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m Please refer to the Installation Guide for details:\n",
      "  \u001b[31m   \u001b[0m https://docs.cupy.dev/en/stable/install.html\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m ************************************************************\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"/home/sun/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 353, in <module>\n",
      "  \u001b[31m   \u001b[0m     main()\n",
      "  \u001b[31m   \u001b[0m   File \"/home/sun/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 335, in main\n",
      "  \u001b[31m   \u001b[0m     json_out['return_val'] = hook(**hook_input['kwargs'])\n",
      "  \u001b[31m   \u001b[0m   File \"/home/sun/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 149, in prepare_metadata_for_build_wheel\n",
      "  \u001b[31m   \u001b[0m     return hook(metadata_directory, config_settings)\n",
      "  \u001b[31m   \u001b[0m   File \"/tmp/pip-build-env-z7wy4590/overlay/lib/python3.10/site-packages/setuptools/build_meta.py\", line 366, in prepare_metadata_for_build_wheel\n",
      "  \u001b[31m   \u001b[0m     self.run_setup()\n",
      "  \u001b[31m   \u001b[0m   File \"/tmp/pip-build-env-z7wy4590/overlay/lib/python3.10/site-packages/setuptools/build_meta.py\", line 480, in run_setup\n",
      "  \u001b[31m   \u001b[0m     super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)\n",
      "  \u001b[31m   \u001b[0m   File \"/tmp/pip-build-env-z7wy4590/overlay/lib/python3.10/site-packages/setuptools/build_meta.py\", line 311, in run_setup\n",
      "  \u001b[31m   \u001b[0m     exec(code, locals())\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 88, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"/tmp/pip-install-66ea4jj2/cupy_6eabe6fe111c476894fc65a07c721595/install/cupy_builder/cupy_setup_build.py\", line 449, in get_ext_modules\n",
      "  \u001b[31m   \u001b[0m     extensions = make_extensions(ctx, compiler, use_cython)\n",
      "  \u001b[31m   \u001b[0m   File \"/tmp/pip-install-66ea4jj2/cupy_6eabe6fe111c476894fc65a07c721595/install/cupy_builder/cupy_setup_build.py\", line 305, in make_extensions\n",
      "  \u001b[31m   \u001b[0m     raise Exception('Your CUDA environment is invalid. '\n",
      "  \u001b[31m   \u001b[0m Exception: Your CUDA environment is invalid. Please check above error log.\n",
      "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n",
      "  \n",
      "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "\u001b[?25h\u001b[1;31merror\u001b[0m: \u001b[1mmetadata-generation-failed\u001b[0m\n",
      "\n",
      "\u001b[31m×\u001b[0m Encountered error while generating package metadata.\n",
      "\u001b[31m╰─>\u001b[0m See above for output.\n",
      "\n",
      "\u001b[1;35mnote\u001b[0m: This is an issue with the package mentioned above, not pip.\n",
      "\u001b[1;36mhint\u001b[0m: See above for details.\n"
     ]
    }
   ],
   "source": [
    "!pip install cupy"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
